services:
  server:
    build:
      context: .
      dockerfile: apps/server/Dockerfile
    restart: unless-stopped
    environment:
      PORT: 8082
    ports:
      - '8082:8082'

  client:
    build:
      context: .
      dockerfile: apps/client/Dockerfile
    restart: unless-stopped
    depends_on:
      - server
    ports:
      - '8081:8081'
